"""empty message

Revision ID: 111e5c43bad3
Revises: 566180bca6c8
Create Date: 2015-08-26 17:24:16.141951

"""

# revision identifiers, used by Alembic.
revision = '111e5c43bad3'
down_revision = '566180bca6c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_sort_code', sa.String(), nullable=False),
    sa.Column('amount_total', sa.Numeric(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'user_orders', 'delivery_method',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column(u'user_orders', 'payment_method',
               existing_type=sa.SMALLINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'user_orders', 'payment_method',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column(u'user_orders', 'delivery_method',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_table('user_withdrawal')
    ### end Alembic commands ###
