"""empty message

Revision ID: 11ac24adc030
Revises: 319c29b1e8ee
Create Date: 2015-07-08 17:57:40.303570

"""

# revision identifiers, used by Alembic.
revision = '11ac24adc030'
down_revision = '319c29b1e8ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('retail_price', sa.Numeric(), nullable=False),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('shipping_price', sa.Numeric(), nullable=True),
    sa.Column('collection_only', sa.Boolean(), nullable=False),
    sa.Column('post_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('location_lat', sa.Numeric(), nullable=True),
    sa.Column('location_lon', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_listings_category_id', 'listings', ['category_id'], unique=False)
    op.create_index(u'ix_listings_color_id', 'listings', ['color_id'], unique=False)
    op.create_index(u'ix_listings_condition_id', 'listings', ['condition_id'], unique=False)
    op.create_index(u'ix_listings_platform_id', 'listings', ['platform_id'], unique=False)
    op.create_index(u'ix_listings_subcategory_id', 'listings', ['subcategory_id'], unique=False)
    op.create_index(u'ix_listings_user_id', 'listings', ['user_id'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_listing_photos_listing_id', 'listing_photos', ['listing_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_listing_photos_listing_id', table_name='listing_photos')
    op.drop_table('listing_photos')
    op.drop_index(u'ix_listings_user_id', table_name='listings')
    op.drop_index(u'ix_listings_subcategory_id', table_name='listings')
    op.drop_index(u'ix_listings_platform_id', table_name='listings')
    op.drop_index(u'ix_listings_condition_id', table_name='listings')
    op.drop_index(u'ix_listings_color_id', table_name='listings')
    op.drop_index(u'ix_listings_category_id', table_name='listings')
    op.drop_table('listings')
    ### end Alembic commands ###
