"""empty message

Revision ID: 136313dcff61
Revises: e04883562f5
Create Date: 2015-07-03 22:01:06.044270

"""

# revision identifiers, used by Alembic.
revision = '136313dcff61'
down_revision = 'e04883562f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('color_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.drop_column('items', u'color')
    op.drop_column('items', u'category')
    op.drop_column('items', u'post_code')
    op.drop_column('items', u'condition')
    op.drop_column('items', u'platform')
    op.create_index(u'ix_items_category_id', 'items', ['category_id'], unique=False)
    op.create_index(u'ix_items_color_id', 'items', ['color_id'], unique=False)
    op.create_index(u'ix_items_condition_id', 'items', ['condition_id'], unique=False)
    op.create_index(u'ix_items_platform_id', 'items', ['platform_id'], unique=False)
    op.create_index(u'ix_items_subcategory_id', 'items', ['subcategory_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_items_subcategory_id', table_name='items')
    op.drop_index(u'ix_items_platform_id', table_name='items')
    op.drop_index(u'ix_items_condition_id', table_name='items')
    op.drop_index(u'ix_items_color_id', table_name='items')
    op.drop_index(u'ix_items_category_id', table_name='items')
    op.add_column('items', sa.Column(u'platform', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column(u'condition', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column(u'post_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column(u'category', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column(u'color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('items', 'subcategory_id')
    op.drop_column('items', 'platform_id')
    op.drop_column('items', 'condition_id')
    op.drop_column('items', 'color_id')
    op.drop_column('items', 'category_id')
    ### end Alembic commands ###
