"""empty message

Revision ID: 163a6ef71145
Revises: cf3e200c0f7
Create Date: 2015-08-31 16:23:36.720324

"""

# revision identifiers, used by Alembic.
revision = '163a6ef71145'
down_revision = 'cf3e200c0f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('visibility', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'visibility')
    ### end Alembic commands ###
