"""empty message

Revision ID: 199feb6f01cc
Revises: 2040c9751d47
Create Date: 2015-09-08 11:42:23.522817

"""

# revision identifiers, used by Alembic.
revision = '199feb6f01cc'
down_revision = '2040c9751d47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reported_listings_listing_id'), 'reported_listings', ['listing_id'], unique=False)
    op.create_index(op.f('ix_reported_listings_user_id'), 'reported_listings', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reported_listings_user_id'), table_name='reported_listings')
    op.drop_index(op.f('ix_reported_listings_listing_id'), table_name='reported_listings')
    op.drop_table('reported_listings')
    ### end Alembic commands ###
