"""empty message

Revision ID: 1aec147defa3
Revises: 2e2fa9dbda8
Create Date: 2015-08-19 17:11:21.710720

"""

# revision identifiers, used by Alembic.
revision = '1aec147defa3'
down_revision = '2e2fa9dbda8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedbacks_to_user_id'), 'user_feedbacks', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedbacks_user_id'), 'user_feedbacks', ['user_id'], unique=False)
    op.add_column(u'user_orders', sa.Column('available_feedback', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user_orders', 'available_feedback')
    op.drop_index(op.f('ix_user_feedbacks_user_id'), table_name='user_feedbacks')
    op.drop_index(op.f('ix_user_feedbacks_to_user_id'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    ### end Alembic commands ###
