"""empty message

Revision ID: 1ec4270f42f1
Revises: 40de1c35b72d
Create Date: 2015-07-10 14:04:14.569658

"""

# revision identifiers, used by Alembic.
revision = '1ec4270f42f1'
down_revision = '40de1c35b72d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_metatags', sa.Column('metatag_type', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_metatags', 'metatag_type')
    ### end Alembic commands ###
