"""empty message

Revision ID: 2040c9751d47
Revises: 38a4d980b73c
Create Date: 2015-09-07 17:15:22.360195

"""

# revision identifiers, used by Alembic.
revision = '2040c9751d47'
down_revision = '38a4d980b73c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reported_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reported_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reported_users_reported_user_id'), 'reported_users', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reported_users_user_id'), 'reported_users', ['user_id'], unique=False)
    op.drop_table('user_reportlist')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reportlist',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reported_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], [u'users.id'], name=u'user_reportlist_reported_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'user_reportlist_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'reported_user_id', name=u'user_reportlist_pkey')
    )
    op.drop_index(op.f('ix_reported_users_user_id'), table_name='reported_users')
    op.drop_index(op.f('ix_reported_users_reported_user_id'), table_name='reported_users')
    op.drop_table('reported_users')
    ### end Alembic commands ###
