"""empty message

Revision ID: 25d8d4d47bd0
Revises: 163a6ef71145
Create Date: 2015-09-01 18:57:10.516328

"""

# revision identifiers, used by Alembic.
revision = '25d8d4d47bd0'
down_revision = '163a6ef71145'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apns_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('available_push_notifications', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('available_push_notifications_types', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_push_notifications_types')
    op.drop_column('users', 'available_push_notifications')
    op.drop_column('users', 'apns_token')
    ### end Alembic commands ###
