"""empty message

Revision ID: 26a1001db94a
Revises: 2d7f11b9a677
Create Date: 2015-08-24 16:37:24.699573

"""

# revision identifiers, used by Alembic.
revision = '26a1001db94a'
down_revision = '2d7f11b9a677'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('previous_price', sa.Numeric(), nullable=True))
    op.add_column('listings', sa.Column('reserve_time', sa.DateTime(), nullable=True))
    op.add_column('listings', sa.Column('reserved_by_user', sa.Boolean(), nullable=True))
    op.add_column('listings', sa.Column('user_who_reserve_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings', 'users', ['user_who_reserve_id'], ['id'])
    op.alter_column('users', 'holiday_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'notify_about_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notify_about_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'holiday_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'user_who_reserve_id')
    op.drop_column('listings', 'reserved_by_user')
    op.drop_column('listings', 'reserve_time')
    op.drop_column('listings', 'previous_price')
    ### end Alembic commands ###
