"""empty message

Revision ID: 272f493f408e
Revises: 1aec147defa3
Create Date: 2015-08-19 18:34:54.221505

"""

# revision identifiers, used by Alembic.
revision = '272f493f408e'
down_revision = '1aec147defa3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    ### end Alembic commands ###
