"""empty message

Revision ID: 27c2a52b6524
Revises: 24d4a48bf25c
Create Date: 2015-08-04 17:40:36.324125

"""

# revision identifiers, used by Alembic.
revision = '27c2a52b6524'
down_revision = '24d4a48bf25c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('date_finish', sa.DateTime(), nullable=True),
    sa.Column('system_status', sa.SmallInteger(), nullable=False),
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=True),
    sa.Column('payment_sum', sa.Numeric(), nullable=True),
    sa.Column('application_fee_sum', sa.Numeric(), nullable=True),
    sa.Column('transaction_status', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_charges_buyer_id'), 'stripe_charges', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_stripe_charges_listing_id'), 'stripe_charges', ['listing_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'offers', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'users', 'stripe_customers', ['stripe_customer_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_stripe_charges_listing_id'), table_name='stripe_charges')
    op.drop_index(op.f('ix_stripe_charges_buyer_id'), table_name='stripe_charges')
    op.drop_table('stripe_charges')
    ### end Alembic commands ###
