"""empty message

Revision ID: 2ba835a5054b
Revises: 547f94d6b144
Create Date: 2015-08-03 15:20:00.264783

"""

# revision identifiers, used by Alembic.
revision = '2ba835a5054b'
down_revision = '547f94d6b144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_card_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'platforms', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column(u'platforms', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column(u'users', sa.Column('stripe_customer_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'stripe_customer_id')
    op.alter_column(u'platforms', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column(u'platforms', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('stripe_customers')
    ### end Alembic commands ###
