"""empty message

Revision ID: 2d7f11b9a677
Revises: 38feff79b3d3
Create Date: 2015-08-23 22:22:02.846461

"""

# revision identifiers, used by Alembic.
revision = '2d7f11b9a677'
down_revision = '38feff79b3d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('response_time', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('user_avatar', sa.String(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('listing_title', sa.String(), nullable=True),
    sa.Column('listing_photo', sa.String(), nullable=True),
    sa.Column('listing_selling_price', sa.Numeric(), nullable=True),
    sa.Column('listing_shipping_price', sa.Numeric(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(), nullable=True),
    sa.Column('comment_offer_price', sa.Numeric(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'user_orders', 'sorting_status',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.add_column(u'users', sa.Column('average_response_time', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('holiday_mode', sa.Boolean(), nullable=False))
    op.add_column(u'users', sa.Column('notify_about_favorite', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'notify_about_favorite')
    op.drop_column(u'users', 'holiday_mode')
    op.drop_column(u'users', 'average_response_time')
    op.alter_column(u'user_orders', 'sorting_status',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.drop_table('user_notifications')
    ### end Alembic commands ###
