"""empty message

Revision ID: 304f798d68a0
Revises: 199feb6f01cc
Create Date: 2015-09-08 15:23:27.277300

"""

# revision identifiers, used by Alembic.
revision = '304f798d68a0'
down_revision = '199feb6f01cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'reported_listings_listing_id_fkey', 'reported_listings', type_='foreignkey')
    op.create_foreign_key(None, 'reported_listings', 'listings', ['listing_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reported_listings', type_='foreignkey')
    op.create_foreign_key(u'reported_listings_listing_id_fkey', 'reported_listings', 'users', ['listing_id'], ['id'])
    ### end Alembic commands ###
