"""empty message

Revision ID: 3266c7635643
Revises: 272f493f408e
Create Date: 2015-08-20 17:52:26.527549

"""

# revision identifiers, used by Alembic.
revision = '3266c7635643'
down_revision = '272f493f408e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_account_address_line1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_address_line2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_post_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_account_sort_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_month', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.alter_column('users', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'birth_month')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'bank_account_sort_code')
    op.drop_column('users', 'bank_account_post_code')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_account_last_name')
    op.drop_column('users', 'bank_account_first_name')
    op.drop_column('users', 'bank_account_city')
    op.drop_column('users', 'bank_account_address_line2')
    op.drop_column('users', 'bank_account_address_line1')
    ### end Alembic commands ###
