"""empty message

Revision ID: 32bff11c1410
Revises: 56cb50da609f
Create Date: 2015-06-10 15:15:21.422033

"""

# revision identifiers, used by Alembic.
revision = '32bff11c1410'
down_revision = '56cb50da609f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_login', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_login')
    ### end Alembic commands ###
