"""empty message

Revision ID: 3889673575d5
Revises: 204fb082d93e
Create Date: 2015-07-22 13:08:22.287234

"""

# revision identifiers, used by Alembic.
revision = '3889673575d5'
down_revision = '204fb082d93e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', u'image_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column(u'image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
