"""empty message

Revision ID: 38a4d980b73c
Revises: 523afd411c5b
Create Date: 2015-09-03 19:11:10.320601

"""

# revision identifiers, used by Alembic.
revision = '38a4d980b73c'
down_revision = '523afd411c5b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('feedback_type', sa.SmallInteger(), nullable=True))
    op.alter_column('users', 'visible_in_find_friends',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'visible_in_find_friends',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user_notifications', 'feedback_type')
    ### end Alembic commands ###
