"""empty message

Revision ID: 38feff79b3d3
Revises: 3266c7635643
Create Date: 2015-08-21 12:37:35.045709

"""

# revision identifiers, used by Alembic.
revision = '38feff79b3d3'
down_revision = '3266c7635643'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_orders', sa.Column('sorting_status', sa.SmallInteger(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'sorting_status')
    ### end Alembic commands ###
