"""empty message

Revision ID: 3b72cfc9b5f9
Revises: 27c2a52b6524
Create Date: 2015-08-05 13:10:31.182974

"""

# revision identifiers, used by Alembic.
revision = '3b72cfc9b5f9'
down_revision = '27c2a52b6524'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.Integer(), nullable=True),
    sa.Column('order_status', sa.SmallInteger(), nullable=False),
    sa.Column('issue_reason', sa.SmallInteger(), nullable=True),
    sa.Column('issue_status', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['charge_id'], ['stripe_charges.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_orders')
    ### end Alembic commands ###
