"""empty message

Revision ID: 3df51bdb7844
Revises: 21162a26971
Create Date: 2015-06-04 14:04:35.547829

"""

# revision identifiers, used by Alembic.
revision = '3df51bdb7844'
down_revision = '21162a26971'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thumbnail', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'thumbnail')
    ### end Alembic commands ###
