"""empty message

Revision ID: 3f92134f5a2e
Revises: dee0f512696
Create Date: 2015-07-16 16:23:23.842582

"""

# revision identifiers, used by Alembic.
revision = '3f92134f5a2e'
down_revision = 'dee0f512696'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_comments_listing_id', 'comments', ['listing_id'], unique=False)
    op.create_index(u'ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('new_price', sa.Numeric(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_offers_listing_id', 'offers', ['listing_id'], unique=False)
    op.create_index(u'ix_offers_user_id', 'offers', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_offers_user_id', table_name='offers')
    op.drop_index(u'ix_offers_listing_id', table_name='offers')
    op.drop_table('offers')
    op.drop_index(u'ix_comments_user_id', table_name='comments')
    op.drop_index(u'ix_comments_listing_id', table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
