"""empty message

Revision ID: 3fd17fd1a8cb
Revises: 4918dafe5f1f
Create Date: 2015-06-22 13:07:26.319571

"""

# revision identifiers, used by Alembic.
revision = '3fd17fd1a8cb'
down_revision = '4918dafe5f1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.create_index(u'ix_users_tags_tag_id', 'users_tags', ['tag_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_tags_tag_id', table_name='users_tags')
    op.drop_column('users_tags', 'tag_id')
    ### end Alembic commands ###
