"""empty message

Revision ID: 40d323ee6b3d
Revises: 304f798d68a0
Create Date: 2015-09-10 14:54:57.712754

"""

# revision identifiers, used by Alembic.
revision = '40d323ee6b3d'
down_revision = '304f798d68a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('low_priority_push_notifications_last_sending', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'low_priority_push_notifications_last_sending')
    ### end Alembic commands ###
