"""empty message

Revision ID: 40de1c35b72d
Revises: 11ac24adc030
Create Date: 2015-07-09 13:02:52.049375

"""

# revision identifiers, used by Alembic.
revision = '40de1c35b72d'
down_revision = '11ac24adc030'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_metatags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_users_metatags_category_id', 'users_metatags', ['category_id'], unique=False)
    op.create_index(u'ix_users_metatags_platform_id', 'users_metatags', ['platform_id'], unique=False)
    op.create_index(u'ix_users_metatags_subcategory_id', 'users_metatags', ['subcategory_id'], unique=False)
    op.create_index(u'ix_users_metatags_user_id', 'users_metatags', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_users_metatags_user_id', table_name='users_metatags')
    op.drop_index(u'ix_users_metatags_subcategory_id', table_name='users_metatags')
    op.drop_index(u'ix_users_metatags_platform_id', table_name='users_metatags')
    op.drop_index(u'ix_users_metatags_category_id', table_name='users_metatags')
    op.drop_table('users_metatags')
    ### end Alembic commands ###
