"""empty message

Revision ID: 423adc75d501
Revises: 32bff11c1410
Create Date: 2015-06-11 17:58:23.814929

"""

# revision identifiers, used by Alembic.
revision = '423adc75d501'
down_revision = '32bff11c1410'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_users_tags_user_id', 'users_tags', ['user_id'], unique=False)
    op.alter_column(u'users', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'users', 'first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(u'ix_users_tags_user_id', table_name='users_tags')
    op.drop_table('users_tags')
    ### end Alembic commands ###
