"""empty message

Revision ID: 4918dafe5f1f
Revises: 32bd61031584
Create Date: 2015-06-22 13:06:58.544046

"""

# revision identifiers, used by Alembic.
revision = '4918dafe5f1f'
down_revision = '32bd61031584'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_tags', u'tag_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_tags', sa.Column(u'tag_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
