"""empty message

Revision ID: 4be90e7c3be1
Revises: 3889673575d5
Create Date: 2015-07-23 12:47:59.975967

"""

# revision identifiers, used by Alembic.
revision = '4be90e7c3be1'
down_revision = '3889673575d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.drop_column('comments', u'user_to_see_id')
    op.create_index(u'ix_comments_offer_id', 'comments', ['offer_id'], unique=False)
    op.drop_index(u'ix_comments_user_to_see_id', table_name='comments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(u'ix_comments_user_to_see_id', 'comments', [u'user_to_see_id'], unique=False)
    op.drop_index(u'ix_comments_offer_id', table_name='comments')
    op.add_column('comments', sa.Column(u'user_to_see_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'offer_id')
    ### end Alembic commands ###
