"""empty message

Revision ID: 4e1127937153
Revises: 1ec4270f42f1
Create Date: 2015-07-14 19:29:19.715598

"""

# revision identifiers, used by Alembic.
revision = '4e1127937153'
down_revision = '1ec4270f42f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('sold', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'sold')
    ### end Alembic commands ###
