"""empty message

Revision ID: 523afd411c5b
Revises: 25d8d4d47bd0
Create Date: 2015-09-02 15:54:24.257453

"""

# revision identifiers, used by Alembic.
revision = '523afd411c5b'
down_revision = '25d8d4d47bd0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('visible_in_find_friends', sa.Boolean(), nullable=False))
    op.alter_column('users', 'available_push_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'available_push_notifications_types',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'available_push_notifications_types',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'available_push_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'visible_in_find_friends')
    op.alter_column('listings', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
