"""empty message

Revision ID: 547f94d6b144
Revises: 1a7cd6417d1e
Create Date: 2015-07-27 16:29:48.481967

"""

# revision identifiers, used by Alembic.
revision = '547f94d6b144'
down_revision = '1a7cd6417d1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('description', sa.String(), nullable=False))
    op.add_column('platforms', sa.Column('image_url', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platforms', 'image_url')
    op.drop_column('platforms', 'description')
    ### end Alembic commands ###
