"""empty message

Revision ID: 566180bca6c8
Revises: 26a1001db94a
Create Date: 2015-08-25 00:25:24.250549

"""

# revision identifiers, used by Alembic.
revision = '566180bca6c8'
down_revision = '26a1001db94a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_charges', 'date_finish')
    op.drop_column('stripe_charges', 'payment_sum_without_application_fee')
    op.drop_column('stripe_charges', 'system_status')
    op.add_column('user_orders', sa.Column('address_id', sa.Integer(), nullable=True))
    op.add_column('user_orders', sa.Column('delivery_method', sa.SmallInteger(), nullable=False))
    op.add_column('user_orders', sa.Column('payment_method', sa.SmallInteger(), nullable=False))
    op.add_column('user_orders', sa.Column('payment_sum', sa.Numeric(), nullable=True))
    op.add_column('user_orders', sa.Column('payment_sum_without_application_fee', sa.Numeric(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_orders', 'payment_sum_without_application_fee')
    op.drop_column('user_orders', 'payment_sum')
    op.drop_column('user_orders', 'payment_method')
    op.drop_column('user_orders', 'delivery_method')
    op.drop_column('user_orders', 'address_id')
    op.add_column('stripe_charges', sa.Column('system_status', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('stripe_charges', sa.Column('payment_sum_without_application_fee', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('stripe_charges', sa.Column('date_finish', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
