"""empty message

Revision ID: 579163594b21
Revises: c87e97ef603
Create Date: 2015-09-25 15:40:36.439234

"""

# revision identifiers, used by Alembic.
revision = '579163594b21'
down_revision = 'c87e97ef603'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_photos', sa.Column('thumbnail_url', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_photos', 'thumbnail_url')
    ### end Alembic commands ###
