"""empty message

Revision ID: 776fcafea45
Revises: 3f92134f5a2e
Create Date: 2015-07-17 12:55:50.430509

"""

# revision identifiers, used by Alembic.
revision = '776fcafea45'
down_revision = '3f92134f5a2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('following_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['following_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'following_user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_followers')
    ### end Alembic commands ###
