"""empty message

Revision ID: af8e964cf77
Revises: 423adc75d501
Create Date: 2015-06-12 16:22:49.698513

"""

# revision identifiers, used by Alembic.
revision = 'af8e964cf77'
down_revision = '423adc75d501'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_items_user_id', 'items', ['user_id'], unique=False)
    op.create_table('item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_item_photos_item_id', 'item_photos', ['item_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_item_photos_item_id', table_name='item_photos')
    op.drop_table('item_photos')
    op.drop_index(u'ix_items_user_id', table_name='items')
    op.drop_table('items')
    ### end Alembic commands ###
