"""empty message

Revision ID: c87e97ef603
Revises: 40d323ee6b3d
Create Date: 2015-09-15 15:40:48.558803

"""

# revision identifiers, used by Alembic.
revision = 'c87e97ef603'
down_revision = '40d323ee6b3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_withdrawal', 'stripe_transfer_id')
    op.alter_column('users', 'low_priority_push_notifications_last_sending',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'low_priority_push_notifications_last_sending',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user_withdrawal', sa.Column('stripe_transfer_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
