"""empty message

Revision ID: cf3e200c0f7
Revises: 111e5c43bad3
Create Date: 2015-08-28 16:28:39.676547

"""

# revision identifiers, used by Alembic.
revision = 'cf3e200c0f7'
down_revision = '111e5c43bad3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('order_available_feedback', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notifications', 'order_available_feedback')
    ### end Alembic commands ###
