"""empty message

Revision ID: e04883562f5
Revises: 31d8b760fa8d
Create Date: 2015-07-01 12:56:20.762485

"""

# revision identifiers, used by Alembic.
revision = 'e04883562f5'
down_revision = '31d8b760fa8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('selling_price', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'selling_price')
    ### end Alembic commands ###
